codecov:
  require_ci_to_pass: yes
  
coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: 70%
        threshold: 2%
        base: auto
        # advanced
        branches:
          - main
        if_ci_failed: error
        only_pulls: false
        flags:
          - unittests
        paths:
          - packages/core/src
    patch: yes

parsers:
  javascript:
    enable_partials: yes
  
comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

flags:
  unittests:
    paths:
      - packages/core/src
      - packages/editor/src 